name: flame_message_stream
description: Streaming messages from game class to any component or even widget
version: 0.0.1+2
repository: https://github.com/ASGAlex/flame_message_stream

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  flame: ^1.6.0
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
